/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 25-mar-2017 19:52:07 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

CREATE INDEX IX_email ON public.auth (email ASC)
;

CREATE INDEX IXFK_Card_Auth ON public.card (auth_id ASC)
;

CREATE INDEX IXFK_Card_CardProvider ON public.card (card_provider_id ASC)
;

CREATE INDEX IXFK_Commentary_Auth ON public.commentary (auth_id ASC)
;

CREATE INDEX IXFK_Commentary_Review ON public.commentary (review_id ASC)
;

CREATE INDEX IX_time_issued ON public.inquiry (time_issued DESC)
;

CREATE INDEX IXFK_InquiryItem_Inquiry ON public.inquiry_item (inquiry_id ASC)
;

CREATE INDEX IXFK_Product_Subcategory ON public.product (subcategory_id ASC)
;

CREATE INDEX IX_code ON public.product (code ASC)
;

CREATE INDEX IXFK_Review_Auth ON public.review (auth_id ASC)
;

CREATE INDEX IXFK_Review_Product ON public.review (product_id ASC)
;

CREATE INDEX IXFK_Review_Ranking ON public.review (ranking_id ASC)
;

CREATE INDEX IXFK_Subcategory_Category ON public.subcategory (category_id ASC)
;

